---
kind: Deployment
metadata:
  annotations:
  name: cloud-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-init
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: cloud-init
    spec:
      containers:
      - env:
        - name: SMD_URL
          value: http://smd:27779
        # TODO can't really predict this in advance without external-dns on the service,
        # and that will vary per site. Probably needs to be injected? There's still the
        # issue where env BASE_URL doesn't work for some of the vendor-data YAML.
        #- name: BASE_URL
        #  value: http://cloud-init
        - name: STORAGE_BACKEND
          value: "quack"
        - name: DB_PATH
          value: "/cidata/cloud-init.db"
        - name: INSECURE
          value: "true"
        - name: DEBUG
          value: "true"
        image: cloud-init-stub
        imagePullPolicy: IfNotPresent
        name: cloud-init
        volumeMounts:
          - mountPath: /cidata
            name: data
        ports:
          - containerPort: 27777
            name: http
            protocol: TCP
        resources: {}
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-cloud-init
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cloud-init
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
  volumeMode: Filesystem
