---
apiVersion: v1
kind: Service
metadata:
  name: cloud-init
spec:
  # cloud-init needs externalTrafficPolicy=Local for a basic LoadBalancer,
  # as it looks up clients by IP and won't recognize kube-proxy IPs.
  # We only have the one replica anyway.
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: cloud-init
  sessionAffinity: None
  type: LoadBalancer
