apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virt-env
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
  source:
    path: 'kustomize/test-node'
    repoURL: 'https://github.com/OpenCHAMI/kube-deploy'
    targetRevision: main
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'

