apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mgmt

resources:
- ../db
- ../init
- ../base

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: v2.7.0
    app.kubernetes.io/component: power-service

images:
- name: power-control-stub
  newName: ghcr.io/openchami/pcs
  newTag: v2.10.0
